### ISSUE TITLE
Colors too bright compared to the Solarized theme screenshots

### ISSUE THREAD

**Issue by nooga** [neolee/solarized-theme-pack#1]
Excuse me if I'm being terribly lame here but I can't make it look like the screenshots on the Solarized webpage. I don't think this is an issue related to your pack but after some search I still don't know where to ask.

![zrzut ekranu 2014-08-13 o 15 56 16](https://cloud.githubusercontent.com/assets/198496/3906293/b65943b2-22f1-11e4-9c05-a900cdd9c082.png)

**Comment by neolee** [comment]
@nooga Can't agree more with you. That's the reason I'm mainly using Tomorrow theme in my Emacs now. I've tried both of two popular Emacs ports of Solarized theme (original repos listed below, one of them is listed in Ethan Schoonover's official page) but still no luck.

https://github.com/sellout/emacs-color-theme-solarized

https://github.com/bbatsov/solarized-emacs
